#! /bin/bash
PS3="Elije una opcion==>";

select menu in "Muestra el path absoluto del directorio actual" "Lista el contenido del directorio actual" "Crea un subdirectorio en el directorio actual" "Borrar un subdirectorio y todo su contenido del directorio actual" Salir;
	do

		if [[
			"$menu" != "Muestra el path absoluto del directorio actual"
			&&
			"$menu" != "Lista el contenido del directorio actual"
			&&
			"$menu" != "Crea un subdirectorio en el directorio actual"
			&&
			"$menu" != "Borrar un subdirectorio y todo su contenido del directorio actual"
			&&
			"$menu" != "Salir"
		]]; then
			echo "escriba un valor valido"

		fi

		if [[ "$menu" == "Salir" ]]; then
			exit;
		fi

		if [[ "$menu" == "Muestra el path absoluto del directorio actual" ]]; then
			pwd
		fi

		if [[ "$menu" == "Lista el contenido del directorio actual" ]]; then
                        ls
                fi

		if [[ "$menu" == "Crea un subdirectorio en el directorio actual" ]]; then
                        read -pDirectorio= DIR

			if [[ "$DIR" =~ ^[a-zA-Z0-9]+$ ]]; then
				mkdir "$DIR"
				echo "se ha creado el directorio $DIR"
			else
				 echo "escribe un valor valido"
			fi
                fi

		if [[ "$menu" == "Borrar un subdirectorio y todo su contenido del directorio actual" ]]; then
                        read -pDirectorio= DIR

			if [[ "$DIR" =~ ^[a-zA-Z0-9]+$ ]]; then
                                rm -r "$DIR"
				echo "se ha borrado el directorio $DIR"
                        else
                                 echo "escribe un valor valido"
                        fi

                fi

	done
