#! /bin/bash

FILES=("$@");

SICE=${#FILES[@]};


for ((i=0; i<$SICE; i++)); do
 	A=$(ls -l ${FILES[$i]} | cut -f3 -d" ")

	if [[ "$A" == "$USER" ]]; then
		chmod +x ${FILES[$i]};
	else
		echo "The file ${FILES[$i]} is not owned by $USER"
	fi
done

